project:
  type: book
  output-dir: docs

book:
  title: "learning-statistics"
  author: "Water Dropwort"
  chapters:
    - index.qmd
    - part: "Bayesian"
      chapters: 
        - bayesian/normal-model.Qmd

format:
  html:
    theme: sketchy