project:
  type: book
  output-dir: docs

book:
  title: "learning-statistics"
  author: "Water Dropwort"
  chapters:
    - index.qmd
    - part: "Basic"
      chapters: 
        - basic/clt-simulation.qmd
    - part: "Bayesian"
      chapters: 
        - bayesian/normal-model.Qmd
        - bayesian/examples/iris-normal-model.qmd
        - bayesian/normal-model-unk-var.qmd

format:
  html:
    theme: cosmo